export const
    TILE_TREE = 1,
    TILE_HOUSE = 100,

    // SERVER SERVER SERVER SERVER

    // API
    API_ERROR_UNKNOWN = 0,
    API_ERROR_UNAUTHORIZED = 1,
    API_ERROR_FIELD_ILLEGAL = 2,
    API_ERROR_FIELD_MISSING = 3,
    API_ERROR_FIELD_DUPLICATE = 4,
    API_ERROR_MAX_SIZE = 5,
    API_ERROR_EXPIRED = 6,
	API_ERROR_NOT_FOUND = 7,
	API_ERROR_USER_NOT_FOUND = 8,
	API_ERROR_CHARACTER_NOT_FOUND = 9,
	API_ERROR_MAP_NOT_FOUND = 10,

    /**
	 * USER
	 */
	USER_FETCH_TYPE_SLIM = 0,
	USER_FETCH_TYPE_FULL = 1,
	USER_FETCH_TYPE_PROFILE_SETTINGS = 2,
	USER_FETCH_TYPE_ACCOUNT_DETAILS = 3,

	USER_GENDER_UNKNOWN = 0,
	USER_GENDER_MALE = 1,
	USER_GENDER_FEMALE = 2,
    USER_GENDER_OTHER = 3,
    
    
	/**
	 * Mongo
	 */
	MONGO_ERROR_VALIDATION = 'ValidationError',
	MONGO_ERROR_KIND_REQUIRED = 'required',
	MONGO_ERROR_KIND_DUPLICATE = 'unique',

	/**
	 * Player
	 */
	PLAYER_TYPE_CUSTOM = 1,
	PLAYER_TYPE_SELF = 2,
	PLAYER_TYPE_HUMAN = 3,
	PLAYER_TYPE_NPC = 4,
	PLAYER_TYPE_OTHER = 5;